### ISSUE TITLE
Better support for narrow windows?

### ISSUE THREAD

**Issue by codl** [3snowp7im/urn#1]
When using a narrow window, if a delta gets a bit too long it will push away the split time and make a scrollbar appear, even if there is more than enough space to fit everything

![](https://cloud.githubusercontent.com/assets/315139/6111974/22b355a6-b08d-11e4-8b13-8b2588b5096b.png) ![](https://cloud.githubusercontent.com/assets/315139/6112054/cb602698-b08d-11e4-9b92-a5cfae6c3da3.png)

**Comment by 3snowp7im** [comment]
Please see if 6ea8558b531088f422326e25155f3ff47383bdce plays nicer with skinny windows

**Comment by codl** [comment]
It is nicer, there's no scrollbar, but now deltas are scattered all over the place

![sscrot](https://cloud.githubusercontent.com/assets/315139/6125060/ab814494-b112-11e4-8fb0-2d700d8abc91.png)

**Comment by 3snowp7im** [comment]
I noticed this last night but forgot to update. Can you try the latest commit?

**Comment by codl** [comment]
This is better but now the scrollbar is back :/

![](https://cloud.githubusercontent.com/assets/315139/6139277/e9ec574c-b189-11e4-9af2-e32839756391.png)

I can use a slightly larger window, I guess

**Comment by 3snowp7im** [comment]
Please try latest commit

**Comment by codl** [comment]
Looking pretty good!

![](https://cloud.githubusercontent.com/assets/315139/6142998/48a63a82-b1c1-11e4-99ed-aa840ab4744f.png)

Although I've lost the ability to set a padding on `.split-title` for some reason, and since `.split` no longer exists I can't set a background image across a split anymore.

**Comment by 3snowp7im** [comment]
Hopefully latest commit resolves the missing split class and continues to work with narrow windows. I seem to have to manually adjust the layout of the splits to get the correct behavior. This oddly has a side effect of "animating" deltas. I'll see if this can be fixed at some point.

**Comment by codl** [comment]
That's perfect. I don't have any more complaints, thank you!

**Comment by 3snowp7im** [comment]
Thanks for opening the issue and seeing it through to resolution. Always happy to make Urn better for everyone :)
