### ISSUE TITLE
Names of keys

### ISSUE THREAD

**Issue by Drenn1** [3snowp7im/urn#11]
I'm trying to figure out what certain keys are named in order to map them. For instance, the back quote (`) symbol, or my numpad Enter key. What's a good way to determine their names?

**Comment by deffi420** [comment]
From [gdkkeysyms.h](https://git.gnome.org/browse/gtk+/tree/gdk/gdkkeysyms.h):

    #define GDK_KEY_grave 0x060
    #define GDK_KEY_quoteleft 0x060

So try "grave" or "quoteleft". To determine the names programmatically, see https://developer.gnome.org/gtk3/stable/gtk3-Keyboard-Accelerators.html#gtk-accelerator-parse

**Comment by deffi420** [comment]
#define GDK_KEY_KP_Enter 0xff8d

"KP_Enter" for mapping numpad enter key.

**Comment by Drenn1** [comment]
Great, thanks a lot.
