### ISSUE TITLE
need guidance to install on ubuntu

### ISSUE THREAD

**Issue by tacgnol3** [3snowp7im/urn#12]
Sorry for opening a ticket for this, but I was wondering how to make this work on ubuntu .... i installed imagemagick, libgtk-3-dev, and libjansson-dev, and I can't make it past the #make install... i have those error : 

user@pc ~/urn $ sudo make install
cp urn-gtk /usr/local/bin
cp urn.desktop /usr/share/applications
for size in 16 22 24 32 36 48 64 72 96 128 256 512; do \
	  convert urn.svg -resize "$size"x"$size" \
	          /usr/share/icons/hicolor/"$size"x"$size"/apps/urn.png ; \
	done
convert.im6: delegate failed `"rsvg-convert" -o "%o" "%i"' @ error/delegate.c/InvokeDelegate/1065.
convert.im6: unable to open image `/tmp/magick-hfaefbvA': No such file or directory @ error/blob.c/OpenBlob/2638.
convert.im6: unable to open file `/tmp/magick-hfaefbvA': No such file or directory @ error/constitute.c/ReadImage/583.
convert.im6: no images defined `/usr/share/icons/hicolor/16x16/apps/urn.png' @ error/convert.c/ConvertImageCommand/3044.
convert.im6: delegate failed `"rsvg-convert" -o "%o" "%i"' @ error/delegate.c/InvokeDelegate/1065.
convert.im6: unable to open image `/tmp/magick-pk87nAmB': No such file or directory @ error/blob.c/OpenBlob/2638.
convert.im6: unable to open file `/tmp/magick-pk87nAmB': No such file or directory @ error/constitute.c/ReadImage/583.
convert.im6: no images defined `/usr/share/icons/hicolor/22x22/apps/urn.png' @ error/convert.c/ConvertImageCommand/3044.
convert.im6: delegate failed `"rsvg-convert" -o "%o" "%i"' @ error/delegate.c/InvokeDelegate/1065.
convert.im6: unable to open image `/tmp/magick-zES2cxhB': No such file or directory @ error/blob.c/OpenBlob/2638.
convert.im6: unable to open file `/tmp/magick-zES2cxhB': No such file or directory @ error/constitute.c/ReadImage/583.
convert.im6: no images defined `/usr/share/icons/hicolor/24x24/apps/urn.png' @ error/convert.c/ConvertImageCommand/3044.
convert.im6: delegate failed `"rsvg-convert" -o "%o" "%i"' @ error/delegate.c/InvokeDelegate/1065.
convert.im6: unable to open image `/tmp/magick-kU1FyGBE': No such file or directory @ error/blob.c/OpenBlob/2638.
convert.im6: unable to open file `/tmp/magick-kU1FyGBE': No such file or directory @ error/constitute.c/ReadImage/583.
convert.im6: no images defined `/usr/share/icons/hicolor/32x32/apps/urn.png' @ error/convert.c/ConvertImageCommand/3044.
convert.im6: delegate failed `"rsvg-convert" -o "%o" "%i"' @ error/delegate.c/InvokeDelegate/1065.
convert.im6: unable to open image `/tmp/magick-rgWv0e6E': No such file or directory @ error/blob.c/OpenBlob/2638.
convert.im6: unable to open file `/tmp/magick-rgWv0e6E': No such file or directory @ error/constitute.c/ReadImage/583.
convert.im6: no images defined `/usr/share/icons/hicolor/36x36/apps/urn.png' @ error/convert.c/ConvertImageCommand/3044.
convert.im6: delegate failed `"rsvg-convert" -o "%o" "%i"' @ error/delegate.c/InvokeDelegate/1065.
convert.im6: unable to open image `/tmp/magick-Mzoh2hZE': No such file or directory @ error/blob.c/OpenBlob/2638.
convert.im6: unable to open file `/tmp/magick-Mzoh2hZE': No such file or directory @ error/constitute.c/ReadImage/583.
convert.im6: no images defined `/usr/share/icons/hicolor/48x48/apps/urn.png' @ error/convert.c/ConvertImageCommand/3044.
convert.im6: delegate failed `"rsvg-convert" -o "%o" "%i"' @ error/delegate.c/InvokeDelegate/1065.
convert.im6: unable to open image `/tmp/magick-ge4Zy5eD': No such file or directory @ error/blob.c/OpenBlob/2638.
convert.im6: unable to open file `/tmp/magick-ge4Zy5eD': No such file or directory @ error/constitute.c/ReadImage/583.
convert.im6: no images defined `/usr/share/icons/hicolor/64x64/apps/urn.png' @ error/convert.c/ConvertImageCommand/3044.
convert.im6: delegate failed `"rsvg-convert" -o "%o" "%i"' @ error/delegate.c/InvokeDelegate/1065.
convert.im6: unable to open image `/tmp/magick-wQvIqJ3D': No such file or directory @ error/blob.c/OpenBlob/2638.
convert.im6: unable to open file `/tmp/magick-wQvIqJ3D': No such file or directory @ error/constitute.c/ReadImage/583.
convert.im6: no images defined `/usr/share/icons/hicolor/72x72/apps/urn.png' @ error/convert.c/ConvertImageCommand/3044.
convert.im6: delegate failed `"rsvg-convert" -o "%o" "%i"' @ error/delegate.c/InvokeDelegate/1065.
convert.im6: unable to open image `/tmp/magick-pF1CM51D': No such file or directory @ error/blob.c/OpenBlob/2638.
convert.im6: unable to open file `/tmp/magick-pF1CM51D': No such file or directory @ error/constitute.c/ReadImage/583.
convert.im6: no images defined `/usr/share/icons/hicolor/96x96/apps/urn.png' @ error/convert.c/ConvertImageCommand/3044.
convert.im6: delegate failed `"rsvg-convert" -o "%o" "%i"' @ error/delegate.c/InvokeDelegate/1065.
convert.im6: unable to open image `/tmp/magick-xkViHkkH': No such file or directory @ error/blob.c/OpenBlob/2638.
convert.im6: unable to open file `/tmp/magick-xkViHkkH': No such file or directory @ error/constitute.c/ReadImage/583.
convert.im6: no images defined `/usr/share/icons/hicolor/128x128/apps/urn.png' @ error/convert.c/ConvertImageCommand/3044.
convert.im6: delegate failed `"rsvg-convert" -o "%o" "%i"' @ error/delegate.c/InvokeDelegate/1065.
convert.im6: unable to open image `/tmp/magick-pung3fJH': No such file or directory @ error/blob.c/OpenBlob/2638.
convert.im6: unable to open file `/tmp/magick-pung3fJH': No such file or directory @ error/constitute.c/ReadImage/583.
convert.im6: no images defined `/usr/share/icons/hicolor/256x256/apps/urn.png' @ error/convert.c/ConvertImageCommand/3044.
convert.im6: delegate failed `"rsvg-convert" -o "%o" "%i"' @ error/delegate.c/InvokeDelegate/1065.
convert.im6: unable to open image `/tmp/magick-pXFK6vHH': No such file or directory @ error/blob.c/OpenBlob/2638.
convert.im6: unable to open file `/tmp/magick-pXFK6vHH': No such file or directory @ error/constitute.c/ReadImage/583.
convert.im6: no images defined `/usr/share/icons/hicolor/512x512/apps/urn.png' @ error/convert.c/ConvertImageCommand/3044.
make: *** [install] Error 1

Thanks in advance !

**Comment by deffi420** [comment]
No idea what that error is all about. What shell are you using? Is imagemagick properly installed via the package manager? Nonetheless, you can remove the for-loop on lines [L23–L26](https://github.com/3snowp7im/urn/blob/608a440286d475b2dec77b466273aba1fc04c8bb/GNUmakefile#L23-L26) of the GNUmakefile and then try to install the program with `sudo make install`.  This does not install the icons, but everything else should work.

**Comment by trysdyn** [comment]
This is kind of old but for the next sap who wanders by, the error above is because the makefile presumes the presnce of the command rsvg-convert, which is part of the librsvg2-bin package. Once you get that, `make install` finishes properly and everything is happy.

**Comment by 2020Mike** [comment]
And for the next person who gets here, I solved on Ubuntu/Mint by using the repositories:

`sudo apt-get update`
`sudo apt-get install librsvg2-bin`
