### ISSUE TITLE
Segmentation fault on opening file

### ISSUE THREAD

**Issue by TheReturningVoid** [3snowp7im/urn#13]
Hello,

Every time I try to open this split file, Urn crashes with a segmentation fault. I'm running Arch Linux (installed urn from AUR package `urn-git`). Here's the split file I'm using:

```json
{
  "title":"Pokemon Blue Any% No Save Corruption"
}
```

If anyone knows how to fix this, that would be greatly appreciated.

Thanks!

**Comment by jsteel44** [comment]
I just came across this issue (also on Arch) and found it needed the splits key at a minimum, so this works:

```
{
  "title": "My Title",
  "splits": [
    {
      "title": "Split Title"
    }
  ]
}
```
See https://github.com/3snowp7im/urn/blob/master/splits/sotn.json for a good example.

**Comment by TheReturningVoid** [comment]
That seems to work. Thanks! Issue can probably be closed now.
