### ISSUE TITLE
Possible to start timer at x seconds?

### ISSUE THREAD

**Issue by bngs** [3snowp7im/urn#29]
Hey, I was wondering if its at all possible to make the timer start at x seconds. I want to start a run at 50 seconds while training so I dont need to watch the intro everytime and use savestates instead.

I've seen through the settings in the README, but I can only find start delay. Did I miss something?

**Comment by resilar** [comment]
Actually urn already supports that through the start_delay option. Simply, add `"start_delay": "-50"` to your splits file (.json). Please explain if this is not a satisfactory workaround (I'd guess it causes some sort of problems if the first 50 seconds of the run span over multiple splits ...)

**Comment by bngs** [comment]
Thank you @resilar!! I read through the options and saw this

> start_delay 	Non-negative delay until timer starts

I thought that meant I cant put -50 as the start delay, but it seems to work.

Thanks for this!

**Comment by alkaris2** [comment]
Setting a delay in my splits file does not make the timer start and the delayed time I want. Do I need to add something else to my theme file in addition to adding the `"start_delay": "-1.50"` ? does it support the decimal format or does it have to be rounded format?
