### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by jbzdarkid** [3snowp7im/urn#3]
Compiling on unix, but getting an odd error: urn-gtk.h doesn't exist, but is included in urn-gtk.c. This seems to cause some compile problems, such as urn-gtk.c:41: error: expected specifier-qualifier-list before ‘GtkApplicationWindow’

**Comment by 3snowp7im** [comment]
What is the output of `make urn-gtk.h`?

**Comment by jbzdarkid** [comment]
unsigned char urn_gtk_css[] = {
  0x2e, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x20, 0x7b, 0x0a, 0x20, 0x20,
  0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2d, 0x63,
  0x6f, 0x6c, 0x6f, 0x72, 0x3a, 0x20, 0x23, 0x30, 0x30, 0x30, 0x3b, 0x0a,
  0x20, 0x20, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x3a, 0x20, 0x23, 0x46, 0x46,
  0x46, 0x3b, 0x0a, 0x7d, 0x0a, 0x2e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x20,
  0x7b, 0x0a, 0x20, 0x20, 0x66, 0x6f, 0x6e, 0x74, 0x2d, 0x73, 0x69, 0x7a,
  0x65, 0x3a, 0x20, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x3b, 0x0a, 0x7d, 0x0a,
  0x2e, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x2d, 0x63, 0x6f, 0x75,
  0x6e, 0x74, 0x20, 0x7b, 0x0a, 0x20, 0x20, 0x63, 0x6f, 0x6c, 0x6f, 0x72,
  0x3a, 0x20, 0x23, 0x39, 0x39, 0x39, 0x3b, 0x0a, 0x7d, 0x0a, 0x0a, 0x2e,
  0x74, 0x69, 0x6d, 0x65, 0x2c, 0x20, 0x2e, 0x64, 0x65, 0x6c, 0x74, 0x61,
  0x20, 0x7b, 0x0a, 0x20, 0x20, 0x66, 0x6f, 0x6e, 0x74, 0x2d, 0x77, 0x65,
  0x69, 0x67, 0x68, 0x74, 0x3a, 0x20, 0x62, 0x6f, 0x6c, 0x64, 0x3b, 0x0a,
  0x7d, 0x0a, 0x0a, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x20, 0x7b, 0x0a,
  0x20, 0x20, 0x66, 0x6f, 0x6e, 0x74, 0x2d, 0x77, 0x65, 0x69, 0x67, 0x68,
  0x74, 0x3a, 0x20, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x3b, 0x0a, 0x20,
  0x20, 0x74, 0x65, 0x78, 0x74, 0x2d, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77,
  0x3a, 0x20, 0x32, 0x70, 0x78, 0x20, 0x32, 0x70, 0x78, 0x20, 0x23, 0x36,
  0x36, 0x36, 0x3b, 0x0a, 0x7d, 0x0a, 0x0a, 0x2e, 0x74, 0x69, 0x6d, 0x65,
  0x72, 0x2d, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x20, 0x7b, 0x0a,
  0x20, 0x20, 0x66, 0x6f, 0x6e, 0x74, 0x2d, 0x73, 0x69, 0x7a, 0x65, 0x3a,
  0x20, 0x33, 0x30, 0x30, 0x25, 0x3b, 0x0a, 0x7d, 0x0a, 0x0a, 0x2e, 0x74,
  0x69, 0x6d, 0x65, 0x72, 0x2d, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x20,
  0x7b, 0x0a, 0x20, 0x20, 0x66, 0x6f, 0x6e, 0x74, 0x2d, 0x73, 0x69, 0x7a,
  0x65, 0x3a, 0x20, 0x32, 0x32, 0x35, 0x25, 0x3b, 0x0a, 0x7d, 0x0a, 0x0a,
  0x2e, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x2d, 0x74, 0x69, 0x6d, 0x65, 0x20,
  0x7b, 0x0a, 0x20, 0x20, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x3a, 0x20, 0x23,
  0x46, 0x46, 0x46, 0x3b, 0x0a, 0x7d, 0x0a, 0x0a, 0x2e, 0x64, 0x6f, 0x6e,
  0x65, 0x20, 0x7b, 0x0a, 0x20, 0x20, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x3a,
  0x20, 0x23, 0x39, 0x39, 0x39, 0x3b, 0x0a, 0x7d, 0x0a, 0x0a, 0x2e, 0x74,
  0x69, 0x6d, 0x65, 0x72, 0x2c, 0x20, 0x2e, 0x64, 0x65, 0x6c, 0x74, 0x61,
  0x20, 0x7b, 0x0a, 0x20, 0x20, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x3a, 0x20,
  0x23, 0x30, 0x43, 0x30, 0x3b, 0x0a, 0x7d, 0x0a, 0x0a, 0x2e, 0x6c, 0x6f,
  0x73, 0x69, 0x6e, 0x67, 0x20, 0x7b, 0x0a, 0x20, 0x20, 0x63, 0x6f, 0x6c,
  0x6f, 0x72, 0x3a, 0x20, 0x23, 0x36, 0x41, 0x36, 0x3b, 0x0a, 0x7d, 0x0a,
  0x0a, 0x2e, 0x62, 0x65, 0x68, 0x69, 0x6e, 0x64, 0x20, 0x7b, 0x0a, 0x20,
  0x20, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x3a, 0x20, 0x23, 0x41, 0x36, 0x36,
  0x3b, 0x0a, 0x7d, 0x0a, 0x0a, 0x2e, 0x62, 0x65, 0x68, 0x69, 0x6e, 0x64,
  0x2e, 0x6c, 0x6f, 0x73, 0x69, 0x6e, 0x67, 0x20, 0x7b, 0x0a, 0x20, 0x20,
  0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x3a, 0x20, 0x23, 0x43, 0x30, 0x30, 0x3b,
  0x0a, 0x7d, 0x0a, 0x0a, 0x2e, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x20, 0x7b,
  0x0a, 0x20, 0x20, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x3a, 0x20, 0x23, 0x39,
  0x39, 0x39, 0x3b, 0x0a, 0x7d, 0x0a, 0x0a, 0x2e, 0x62, 0x65, 0x73, 0x74,
  0x2d, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x20, 0x7b, 0x0a, 0x20,
  0x20, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x3a, 0x20, 0x23, 0x46, 0x39, 0x30,
  0x3b, 0x0a, 0x7d, 0x0a, 0x0a, 0x2e, 0x62, 0x65, 0x73, 0x74, 0x2d, 0x73,
  0x70, 0x6c, 0x69, 0x74, 0x20, 0x7b, 0x0a, 0x20, 0x20, 0x63, 0x6f, 0x6c,
  0x6f, 0x72, 0x3a, 0x20, 0x23, 0x39, 0x39, 0x46, 0x3b, 0x0a, 0x7d, 0x0a,
  0x0a, 0x2e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x70,
  0x6c, 0x69, 0x74, 0x20, 0x7b, 0x0a, 0x20, 0x20, 0x62, 0x61, 0x63, 0x6b,
  0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2d, 0x63, 0x6f, 0x6c, 0x6f, 0x72,
  0x3a, 0x20, 0x72, 0x67, 0x62, 0x61, 0x28, 0x31, 0x32, 0x37, 0x2c, 0x20,
  0x31, 0x32, 0x37, 0x2c, 0x20, 0x32, 0x35, 0x35, 0x2c, 0x20, 0x30, 0x2e,
  0x33, 0x29, 0x3b, 0x0a, 0x7d, 0x0a, 0x0a, 0x2e, 0x73, 0x70, 0x6c, 0x69,
  0x74, 0x2d, 0x6c, 0x61, 0x73, 0x74, 0x20, 0x7b, 0x0a, 0x20, 0x20, 0x62,
  0x6f, 0x72, 0x64, 0x65, 0x72, 0x2d, 0x74, 0x6f, 0x70, 0x3a, 0x20, 0x31,
  0x70, 0x78, 0x20, 0x23, 0x46, 0x46, 0x46, 0x20, 0x73, 0x6f, 0x6c, 0x69,
  0x64, 0x3b, 0x0a, 0x7d, 0x0a
};
unsigned int urn_gtk_css_len = 689;


I still get that warning on line 41.

**Comment by 3snowp7im** [comment]
Is that the output to stdout when you run the command `make urn-gtk.h`? This instead looks like the contents of urn-gtk.h, which should be made by that recipe. If you see this on stdout, there is something wrong with your dev environment. That output is supposed to be piped to urn-gtk.h instead of being printed.

**Comment by jbzdarkid** [comment]
Sorry, that is the contents of urn-gtk.h. I see no output when running make urn-gtk.h

Looking at my files, it seems like I have gtk-2.0 not 3.0, as I'm missing a few files.

**Comment by 3snowp7im** [comment]
No plans on supporting gtk-2.0 at the moment. If you can install gtk-3.0 and have trouble building, please open a new issue.
