### ISSUE TITLE
How do you make splits?

### ISSUE THREAD

**Issue by drsquirrelphd** [3snowp7im/urn#47]
For awhile I've been using LiveSplits One but would like to use a timer that doesn't require me have an internet browser open. After looking around for a long time I finally got Urn working but I'm having problems with the splits. I can use Splits.io to import some of my older splits and export them to Urn but they don't display the name of the game or the category I'm running. Also if I export splits that I didn't import the Urn window is blank. 
So my question is how does one make new splits for Urn? The Read Me is sorely lacking in anything that can help a person who doesn't have any technical skills.

**Comment by dmwit** [comment]
To display the name of the game and category, simply open the splits `.json` file and modify the `title` field to say whatever you want.

I don't understand what "export splits that I didn't import" means. Can you describe the exact sequence of actions you take, what behavior you expect urn to display, and what outcome you observe instead?

**Comment by drsquirrelphd** [comment]
Sorry for the delay.
Thanks for the help with the title. I thought there was some way to make splits in URN.
The thing about exporting was worded poorly, I should have said splits made by other people on Splits.io, sorry. But the thing about opening the .json file lead me to find an added comma in the exported file. Once that was gone everything worked fine.
Thanks again.
